// Complete website copy per locale. No implicit English fallback.
const keys = ['name','overview','partners','privacy','language','skip','eyebrow','headline','intro','review','explore','status','statusBody','recognized','suggestions','languages','howTitle','steps','screenTitle','screenCaption','coverageTitle','coverageBody','categories','partnerTitle','partnerBody','principles','readyTitle','readyBody','contactTitle','contactBody','emailLabel','print','privacyIntro','privacySections','footer','back','updated'];
const make = (values) => { if(values.length !== keys.length) throw Error(`Locale schema: ${values[0]} ${values.length}/${keys.length}`); return Object.fromEntries(keys.map((key,i)=>[key,values[i]])); };
export const locales = {
en: make([
'English','The extension','For partners','Privacy','Language','Skip to content','pikvia · BY RUSHLABS','A helpful next step, for every trip.','A Chrome extension that helps travelers discover relevant services as they browse. Clear choices. Relevant suggestions. Every visit starts with a click.','Discuss a partnership','See how it works','Development preview','Version 0.4.4 · Not yet listed in the Chrome Web Store.','Recognized consumer services','Suggestions at a time','Website languages','From browsing to discovery.',
[['Browse a supported site','The extension recognizes the site and page category on your device.'],['Explore relevant options','Up to three alternative services appear in the popup or a compact page panel.'],['Choose where to go','A recommendation opens in a new tab only when the user clicks it.']],
'A small interface. A useful next step.','Actual compiled popup in Korean, captured in a development UI test (v0.4.4). Service names identify their services; they do not imply affiliation or endorsement.','Built around the travel journey.','The catalog covers travel and related services. Recognition does not mean an approved affiliate relationship.',
['Stays','Flights & transport','Tours & tickets','eSIM & connectivity','Car rental & luggage storage','Shopping & related services'],
'A transparent referral channel.','For affiliate networks and advertisers reviewing browser-extension traffic. We seek program-specific permission before activating monetized links.',
[['User-initiated visits','No automatic redirects or background affiliate-link application on real sites.'],['Visible commission disclosure','Configured affiliate links are identified in the interface. Purchases may earn commission for the configured account owner.'],['Respect for existing attribution','Detected publisher parameters are preserved. The extension does not read cookies.'],['Approval before activation','Without approved configuration, recommendations use ordinary website links. No verified discounts or cashback are currently enabled.']],
'Available for technical review.','A development build is available on request. Store submission is on hold pending verified benefits, program approval and final review. Audience size, conversions and revenue have not been verified.',
'Let’s review the fit.','Ask RushLabs for a review build, a referral-flow walkthrough or a discussion of your program’s browser-extension requirements.','Partner enquiries','Print this overview',
'This page summarizes how the current extension and this website handle data. The full extension policy is available in English and Korean.',
[['On-device processing','Supported-page URLs and limited DOM geometry are processed locally for detection and UI placement. The current general build does not send browsing URLs to the production link API.'],['Storage and control','Settings, language, comparison selections and public affiliate IDs stay in extension local storage. Session or background-memory records support temporary processing. Disable recommendations, restrict site access or uninstall to remove extension storage.'],['External destinations','Clicking a configured affiliate link can send the public affiliate ID and destination to the merchant or network. Their policies apply. The extension does not request passwords or payment details, collect browsing-history databases, or include analytics SDKs.'],['This website','No analytics, advertising trackers or contact forms. GitHub Pages may process request metadata to serve the site. A selected language may be saved in this browser. Email opens your mail app; sending an email shares its contents with RushLabs.']],
'Independent software by RushLabs, South Korea. Program approval and store publication are separate from this introduction.','Back to overview','Updated 8 October 2026'
]),
ko: make([
'한국어','확장 프로그램','파트너 안내','개인정보','언어','본문으로 이동','pikvia · RUSHLABS','여행의 다음 선택을, 더 편하게.','여행 사이트를 탐색하면서 관련 서비스를 발견하도록 돕는 Chrome 확장 프로그램입니다. 필요한 추천을 살펴보고, 사용자가 직접 다음 방문을 선택합니다.','제휴 문의하기','이용 흐름 보기','개발 미리보기','버전 0.4.4 · Chrome 웹 스토어에는 아직 등록되지 않았습니다.','인식하는 소비자 서비스','한 번에 제공하는 추천','소개 페이지 지원 언어','탐색에서 발견까지.',
[['지원 사이트 방문','기기에서 현재 사이트와 페이지의 카테고리를 인식합니다.'],['관련 서비스 확인','팝업 또는 작은 페이지 패널에서 최대 3개의 대체 서비스를 제공합니다.'],['직접 선택하여 이동','사용자가 추천을 클릭했을 때만 새 탭으로 이동합니다.']],
'작은 화면에서 만나는 새로운 선택.','개발 UI 테스트에서 캡처한 실제 한국어 팝업입니다(v0.4.4). 서비스 이름은 식별용이며 공식 제휴나 보증을 의미하지 않습니다.','여행의 여러 순간을 연결합니다.','여행 및 관련 서비스 카탈로그를 제공합니다. 서비스 인식이 제휴 승인을 의미하지는 않습니다.',
['숙박','항공권·교통','투어·입장권','eSIM·통신','렌터카·짐보관','쇼핑·관련 서비스'],
'투명하게 설명하는 추천 경로.','브라우저 확장 유입을 검토하는 제휴 네트워크와 광고주를 위한 안내입니다. 수익화 링크 활성화 전 프로그램별 사용 허용을 확인합니다.',
[['사용자 클릭으로 시작','실제 사이트에서 자동 이동이나 백그라운드 제휴 링크 적용을 하지 않습니다.'],['명확한 수수료 고지','설정된 제휴 링크는 화면에 표시합니다. 구매 시 설정된 제휴 계정 운영자에게 수수료가 발생할 수 있습니다.'],['기존 추적 정보 보호','감지된 publisher 파라미터를 유지하며 사이트 쿠키는 읽지 않습니다.'],['승인 후 활성화','승인된 설정이 없으면 일반 사이트 링크를 제공합니다. 현재 검증된 할인·캐시백은 활성화되지 않았습니다.']],
'기술 검토를 위한 준비.','요청 시 개발 빌드를 제공합니다. 검증된 혜택, 프로그램 승인, 최종 검토 전까지 스토어 제출은 보류 중입니다. 이용자 수·전환·수익 실적은 검증되지 않았습니다.',
'프로그램과의 적합성을 함께 검토합니다.','RushLabs에 검토용 빌드, 추천 흐름 시연 또는 프로그램의 브라우저 확장 요건에 관한 상담을 요청하세요.','제휴 문의','소개 자료 인쇄',
'현재 확장 프로그램과 이 웹사이트의 정보 처리 방식을 요약합니다. 전체 확장 개인정보처리방침은 한국어와 영어로 제공합니다.',
[['기기 내 처리','지원 페이지 URL과 제한된 DOM 위치·크기를 기기에서 처리해 사이트를 인식하고 UI를 배치합니다. 현재 일반 빌드는 방문 URL을 운영 링크 API에 보내지 않습니다.'],['저장과 제어','설정·언어·비교 선택·공개 제휴 ID는 확장 로컬 저장소에 보관합니다. 임시 처리는 세션 또는 백그라운드 메모리를 사용합니다. 추천을 끄거나 사이트 접근을 제한할 수 있고 확장 삭제 시 저장소가 제거됩니다.'],['외부 사이트 이동','설정된 제휴 링크를 클릭하면 공개 제휴 ID와 목적지가 판매자 또는 네트워크에 전달될 수 있으며 해당 정책이 적용됩니다. 비밀번호·결제정보를 요청하지 않고 방문 기록 DB나 분석 SDK를 운영하지 않습니다.'],['이 웹사이트','분석 도구·광고 추적기·문의 양식이 없습니다. GitHub Pages는 사이트 제공을 위해 요청 메타데이터를 처리할 수 있습니다. 선택 언어는 브라우저에 저장될 수 있습니다. 이메일 버튼은 메일 앱을 열며 발송 시 내용이 RushLabs에 전달됩니다.']],
'대한민국 RushLabs가 개발하는 독립 소프트웨어입니다. 프로그램 승인과 스토어 출시는 이 소개 자료와 별도로 진행됩니다.','소개로 돌아가기','2026년 10월 8일 갱신'
]),
ja: make([
'日本語','拡張機能','パートナー向け','プライバシー','言語','本文へ','pikvia · RUSHLABS','旅の次の選択を、もっと身近に。','旅行サイトの閲覧中に関連サービスを見つけるChrome拡張機能です。おすすめを確認し、訪問先はユーザー自身が選びます。','提携について相談','使い方を見る','開発プレビュー','バージョン0.4.4 · Chromeウェブストア未公開。','認識する消費者向けサービス','一度に表示する候補','ウェブサイトの対応言語','閲覧から、新しい発見へ。',
[['対応サイトを閲覧','端末上でサイトとページのカテゴリを認識します。'],['関連する候補を確認','ポップアップまたは小さなパネルに最大3つの代替サービスを表示します。'],['自分で訪問先を選択','クリックした場合にのみ新しいタブが開きます。']],
'小さな画面で、次の選択を。','開発UIテストで撮影した実際の韓国語ポップアップ（v0.4.4）。サービス名は識別用で、提携や推奨を意味しません。','旅のさまざまな場面に。','旅行と関連サービスを収録しています。サイトの認識はアフィリエイト承認を意味しません。',
['宿泊','航空券・交通','ツアー・チケット','eSIM・通信','レンタカー・荷物預かり','買い物・関連サービス'],
'透明性のある送客経路。','拡張機能からの流入を審査するネットワークと広告主向けの資料です。収益化リンクは各プログラムの許可を確認してから有効にします。',
[['ユーザーのクリックが起点','実際のサイトで自動転送やバックグラウンドのリンク適用は行いません。'],['報酬の明確な表示','設定済みの提携リンクを画面で示します。購入により設定されたアカウントの運営者に報酬が生じる場合があります。'],['既存の帰属情報を保護','検出したpublisherパラメータを保持し、Cookieは読み取りません。'],['承認後に有効化','承認済み設定がなければ通常リンクを使用します。検証済みの割引・キャッシュバックは現在ありません。']],
'技術審査に対応します。','開発ビルドはお問い合わせください。検証済み特典、プログラム承認、最終確認までストア提出は保留中です。利用者数・コンバージョン・収益は未検証です。',
'プログラムとの適合性を確認。','審査用ビルド、送客フローの説明、拡張機能に関する要件についてRushLabsへご相談ください。','提携のお問い合わせ','紹介資料を印刷',
'現在の拡張機能と本サイトのデータ処理概要です。拡張機能の完全な方針は英語と韓国語で提供しています。',
[['端末上での処理','対応ページのURLと限定的なDOM位置・寸法を端末内で処理します。通常ビルドは閲覧URLを本番リンクAPIへ送信しません。'],['保存と制御','設定、言語、比較対象、公開アフィリエイトIDは拡張機能のローカル保存領域に保持します。一時処理にはセッションまたはメモリを使用します。おすすめの停止、サイト権限の制限、アンインストールによるデータ削除が可能です。'],['外部の訪問先','提携リンクのクリック時に公開IDと訪問先が事業者やネットワークへ送られる場合があります。各社の方針が適用されます。パスワード・決済情報は要求せず、閲覧履歴DBや解析SDKは使用しません。'],['このウェブサイト','解析、広告トラッカー、問い合わせフォームはありません。GitHub Pagesは配信に必要なリクエスト情報を処理する場合があります。選択言語はブラウザに保存される場合があります。メール送信時の内容はRushLabsに届きます。']],
'韓国のRushLabsによる独立したソフトウェアです。プログラム承認とストア公開は本資料とは別です。','紹介に戻る','2026年10月8日更新'
]),
'zh-CN': make([
'简体中文','扩展程序','合作伙伴','隐私','语言','跳转到正文','pikvia · RUSHLABS','让旅程的下一步，更轻松。','在浏览旅行网站时帮助发现相关服务的Chrome扩展程序。查看适合的推荐，由用户自己选择下一次访问。','洽谈合作','了解使用流程','开发预览','版本0.4.4 · 尚未在Chrome应用商店发布。','可识别的消费者服务','每次提供的推荐','网站支持语言','从浏览，到发现。',
[['访问支持的网站','在设备上识别网站和页面类别。'],['查看相关选择','在弹出窗口或小型页面面板中显示最多3个替代服务。'],['自己选择目的地','只有点击推荐时，才会在新标签页中打开链接。']],
'小巧的界面，实用的下一步。','开发UI测试中截取的真实韩语弹出窗口（v0.4.4）。服务名称仅用于识别，不代表合作或背书。','覆盖旅行的多个环节。','目录涵盖旅行及相关服务。识别网站不等于已获联盟营销批准。',
['住宿','机票与交通','游览与门票','eSIM与通信','租车与行李寄存','购物及相关服务'],
'透明的推荐流量渠道。','为审核浏览器扩展流量的联盟网络和广告主提供信息。启用变现链接前，先确认每个项目的使用许可。',
[['用户主动点击','在真实网站上不会自动跳转或在后台应用联盟链接。'],['明确披露佣金','已配置的联盟链接会在界面标识。购买可能为已配置账户的运营方带来佣金。'],['保护现有归因','保留检测到的publisher参数，不读取网站Cookie。'],['批准后启用','未有已批准配置时使用普通链接。目前未启用经验证的折扣或返现。']],
'可供技术审核。','可按需提供开发版本。商店提交暂缓，等待验证优惠、项目批准和最终审核。用户规模、转化及收入尚未验证。',
'一起评估合作适配性。','联系RushLabs，申请审核版本、了解推荐流程，或讨论项目对浏览器扩展的要求。','合作咨询','打印介绍',
'以下概述当前扩展和本网站的数据处理。完整扩展隐私政策提供英语和韩语版本。',
[['设备内处理','支持页面的URL及有限DOM位置和尺寸在设备内处理，用于识别与界面布局。当前普通版本不向生产链接API发送浏览URL。'],['存储与控制','设置、语言、比较选择和公开联盟ID保存在扩展本地存储。临时处理使用会话或后台内存。可关闭推荐、限制网站权限，卸载后移除扩展存储。'],['外部目的地','点击配置好的联盟链接可能向商家或网络发送公开ID和目的地址，适用其政策。不要求密码或支付信息，不建立浏览历史数据库，不使用分析SDK。'],['本网站','无分析工具、广告追踪器或联系表单。GitHub Pages可能为提供网站处理请求元数据。语言选择可保存在浏览器。邮件按钮打开邮件应用，发送后内容会分享给RushLabs。']],
'由韩国RushLabs开发的独立软件。项目批准和商店发布与本介绍独立进行。','返回介绍','更新于2026年10月8日'
]),
'zh-TW': make([
'繁體中文','擴充功能','合作夥伴','隱私','語言','跳至主內容','pikvia · RUSHLABS','讓旅程的下一步，更輕鬆。','在瀏覽旅遊網站時協助探索相關服務的Chrome擴充功能。查看合適的推薦，由使用者自行選擇下一次造訪。','洽談合作','了解使用流程','開發預覽','版本0.4.4 · 尚未於Chrome線上應用程式商店發布。','可辨識的消費者服務','每次提供的推薦','網站支援語言','從瀏覽，到探索。',
[['造訪支援網站','在裝置上辨識網站與頁面類別。'],['查看相關選擇','在彈出視窗或小型頁面面板顯示最多3個替代服務。'],['自行選擇目的地','只有點擊推薦時，才會在新分頁開啟連結。']],
'小巧介面，實用的下一步。','開發UI測試擷取的實際韓語彈出視窗（v0.4.4）。服務名稱僅供識別，不代表合作或背書。','涵蓋旅程的不同環節。','目錄包含旅遊與相關服務。辨識網站不表示已獲聯盟行銷核准。',
['住宿','機票與交通','行程與門票','eSIM與通訊','租車與行李寄存','購物及相關服務'],
'透明的推薦流量管道。','提供審查瀏覽器擴充功能流量的聯盟網路與廣告主參考。啟用營利連結前，先確認各計畫的使用許可。',
[['使用者主動點擊','真實網站不會自動轉址或在背景套用聯盟連結。'],['明確揭露佣金','已設定的聯盟連結會在介面標示。購買可能為設定帳戶的營運者帶來佣金。'],['保護既有歸因','保留偵測到的publisher參數，不讀取網站Cookie。'],['核准後啟用','沒有經核准的設定時使用一般連結。目前未啟用經驗證的折扣或現金回饋。']],
'可供技術審查。','可依需求提供開發版本。商店提交暫緩，等待驗證優惠、計畫核准與最終審查。使用者規模、轉換和收入尚未驗證。',
'一起評估合作適合度。','聯絡RushLabs，索取審查版本、了解推薦流程，或討論計畫對瀏覽器擴充功能的要求。','合作洽詢','列印介紹',
'以下摘要目前擴充功能與本網站的資料處理。完整擴充功能隱私政策提供英文與韓文版本。',
[['裝置內處理','支援頁面的URL及有限DOM位置與尺寸在裝置內處理，用於辨識與介面配置。目前一般版本不向正式連結API傳送瀏覽URL。'],['儲存與控制','設定、語言、比較選擇及公開聯盟ID保存在擴充功能本機儲存。暫時處理使用工作階段或背景記憶體。可關閉推薦、限制網站權限，解除安裝後移除擴充功能儲存。'],['外部目的地','點擊設定好的聯盟連結可能向商家或網路傳送公開ID與目的地，適用其政策。不要求密碼或付款資料，不建立瀏覽紀錄資料庫，不使用分析SDK。'],['本網站','無分析工具、廣告追蹤器或聯絡表單。GitHub Pages可能為提供網站處理請求中繼資料。語言選擇可儲存於瀏覽器。郵件按鈕開啟郵件應用程式，寄出後內容會分享給RushLabs。']],
'由韓國RushLabs開發的獨立軟體。計畫核准與商店發布與本介紹分別進行。','返回介紹','更新於2026年10月8日'
]),
de: make([
'Deutsch','Die Erweiterung','Für Partner','Datenschutz','Sprache','Zum Inhalt','pikvia · RUSHLABS','Der nächste Schritt auf Ihrer Reise.','Eine Chrome-Erweiterung, die beim Surfen passende Reisedienste vorschlägt. Nutzer prüfen die Auswahl und entscheiden selbst, welche Website sie besuchen.','Partnerschaft besprechen','So funktioniert es','Entwicklungsvorschau','Version 0.4.4 · Noch nicht im Chrome Web Store veröffentlicht.','Erkannte Verbraucherdienste','Vorschläge gleichzeitig','Sprachen der Website','Vom Stöbern zum Entdecken.',
[['Unterstützte Website besuchen','Website und Seitenkategorie werden auf dem Gerät erkannt.'],['Passende Optionen entdecken','Bis zu drei Alternativen erscheinen im Popup oder in einem kleinen Panel.'],['Besuch selbst auswählen','Erst ein Klick öffnet die Empfehlung in einem neuen Tab.']],
'Kleine Oberfläche. Hilfreiche Auswahl.','Echtes koreanisches Popup aus einem Entwicklungs-UI-Test (v0.4.4). Dienstnamen dienen der Identifikation und bedeuten keine Partnerschaft oder Empfehlung durch die Anbieter.','Für verschiedene Etappen der Reise.','Der Katalog umfasst Reise- und verwandte Dienste. Erkennung bedeutet keine Affiliate-Zulassung.',
['Unterkünfte','Flüge & Verkehr','Touren & Tickets','eSIM & Verbindung','Mietwagen & Gepäckaufbewahrung','Shopping & verwandte Dienste'],
'Ein transparenter Vermittlungskanal.','Informationen für Netzwerke und Werbetreibende, die Zugriffe aus Browser-Erweiterungen prüfen. Monetarisierte Links erfordern die Erlaubnis des jeweiligen Programms.',
[['Vom Nutzer ausgelöst','Keine automatischen Weiterleitungen oder Affiliate-Link-Anwendung im Hintergrund auf echten Websites.'],['Sichtbare Provisionshinweise','Konfigurierte Affiliate-Links sind gekennzeichnet. Käufe können dem eingestellten Kontobetreiber Provisionen bringen.'],['Bestehende Zuordnung schützen','Erkannte Publisher-Parameter bleiben erhalten. Cookies werden nicht gelesen.'],['Aktivierung nach Freigabe','Ohne genehmigte Konfiguration werden normale Links genutzt. Verifizierte Rabatte oder Cashback sind derzeit nicht aktiviert.']],
'Für technische Prüfung verfügbar.','Ein Entwicklungsbuild ist auf Anfrage erhältlich. Die Store-Einreichung wartet auf verifizierte Vorteile, Programmfreigaben und abschließende Prüfung. Nutzerzahlen, Conversions und Einnahmen sind nicht verifiziert.',
'Gemeinsam die Eignung prüfen.','Fragen Sie RushLabs nach einem Prüfbuild, einer Vorstellung des Vermittlungsablaufs oder den Anforderungen Ihres Programms an Erweiterungen.','Partneranfragen','Übersicht drucken',
'Überblick zur Datenverarbeitung der aktuellen Erweiterung und dieser Website. Die vollständige Erweiterungsrichtlinie ist auf Englisch und Koreanisch verfügbar.',
[['Verarbeitung auf dem Gerät','URLs unterstützter Seiten und begrenzte DOM-Geometrie werden lokal verarbeitet. Der allgemeine Build sendet keine besuchten URLs an die produktive Link-API.'],['Speicherung und Kontrolle','Einstellungen, Sprache, Vergleichsauswahl und öffentliche Affiliate-IDs bleiben im lokalen Erweiterungsspeicher. Temporäre Verarbeitung nutzt Sitzungsspeicher oder Arbeitsspeicher. Empfehlungen lassen sich deaktivieren, Website-Zugriffe beschränken und Daten durch Deinstallation entfernen.'],['Externe Ziele','Ein Klick auf einen konfigurierten Affiliate-Link kann öffentliche IDs und das Ziel an Händler oder Netzwerke übermitteln. Deren Richtlinien gelten. Keine Abfrage von Passwörtern oder Zahlungsdaten, keine Verlaufsdatenbank und keine Analyse-SDKs.'],['Diese Website','Keine Analysewerkzeuge, Werbetracker oder Kontaktformulare. GitHub Pages kann zur Bereitstellung Anfragemetadaten verarbeiten. Die Sprachauswahl kann im Browser gespeichert werden. E-Mails öffnen die Mail-App; versandte Inhalte gehen an RushLabs.']],
'Unabhängige Software von RushLabs, Südkorea. Programmfreigabe und Store-Veröffentlichung erfolgen getrennt von dieser Vorstellung.','Zur Übersicht','Aktualisiert am 8. Oktober 2026'
]),
fr: make([
'Français','L’extension','Pour les partenaires','Confidentialité','Langue','Aller au contenu','pikvia · RUSHLABS','Le prochain choix de votre voyage.','Une extension Chrome pour découvrir des services pertinents en parcourant les sites de voyage. Les utilisateurs consultent les suggestions et choisissent leur prochaine visite.','Parlons partenariat','Voir le fonctionnement','Aperçu de développement','Version 0.4.4 · Pas encore publiée sur le Chrome Web Store.','Services grand public reconnus','Suggestions à la fois','Langues du site','De la navigation à la découverte.',
[['Visiter un site compatible','Le site et la catégorie de la page sont reconnus sur l’appareil.'],['Découvrir des options pertinentes','Jusqu’à trois alternatives apparaissent dans la fenêtre ou un petit panneau.'],['Choisir sa destination','Un nouvel onglet s’ouvre uniquement lorsque l’utilisateur clique.']],
'Une petite interface. Un choix utile.','Véritable fenêtre en coréen, capturée lors d’un test de développement (v0.4.4). Les noms identifient les services sans impliquer de partenariat ni de caution.',
'Pour les différentes étapes du voyage.','Le catalogue couvre le voyage et les services associés. La reconnaissance d’un site ne signifie pas un agrément d’affiliation.',
['Hébergements','Vols et transports','Visites et billets','eSIM et connexion','Location de voiture et consignes','Achats et services associés'],
'Un canal de recommandation transparent.','Pour les réseaux et annonceurs qui examinent le trafic des extensions. L’autorisation de chaque programme est vérifiée avant l’activation des liens monétisés.',
[['Visites initiées par l’utilisateur','Aucune redirection automatique ni application de liens affiliés en arrière-plan sur les sites réels.'],['Commission clairement indiquée','Les liens affiliés configurés sont identifiés. Les achats peuvent rémunérer l’exploitant du compte configuré.'],['Respect de l’attribution existante','Les paramètres publisher détectés sont préservés. Aucun cookie n’est lu.'],['Activation après accord','Sans configuration approuvée, des liens ordinaires sont utilisés. Aucune remise ni cashback vérifiés ne sont activés actuellement.']],
'Disponible pour examen technique.','Un build de développement est disponible sur demande. La soumission au store attend des avantages vérifiés, l’accord des programmes et l’examen final. Audience, conversions et revenus ne sont pas vérifiés.',
'Évaluons la compatibilité.','Demandez à RushLabs un build de test, une présentation du parcours de recommandation ou un échange sur les exigences de votre programme.','Demandes de partenariat','Imprimer la présentation',
'Résumé du traitement des données par l’extension actuelle et ce site. La politique complète de l’extension est disponible en anglais et en coréen.',
[['Traitement sur l’appareil','Les URL des pages compatibles et une géométrie DOM limitée sont traitées localement. Le build général n’envoie pas les URL consultées à l’API de liens en production.'],['Stockage et contrôle','Réglages, langue, sélections de comparaison et identifiants affiliés publics restent dans le stockage local de l’extension. Le traitement temporaire utilise la session ou la mémoire. Désactivez les suggestions, limitez les accès ou désinstallez pour supprimer ce stockage.'],['Destinations externes','Un clic sur un lien affilié configuré peut transmettre l’identifiant public et la destination au marchand ou au réseau. Leurs politiques s’appliquent. Aucun mot de passe ni donnée de paiement demandés, aucune base d’historique ni SDK analytique.'],['Ce site','Aucun outil analytique, traceur publicitaire ou formulaire de contact. GitHub Pages peut traiter des métadonnées de requête pour servir le site. La langue choisie peut être enregistrée dans le navigateur. Un courriel envoyé partage son contenu avec RushLabs.']],
'Logiciel indépendant de RushLabs, Corée du Sud. L’agrément des programmes et la publication en store sont distincts de cette présentation.','Retour à la présentation','Mis à jour le 8 octobre 2026'
]),
es: make([
'Español','La extensión','Para socios','Privacidad','Idioma','Ir al contenido','pikvia · RUSHLABS','El siguiente paso de tu viaje.','Una extensión de Chrome para descubrir servicios relevantes al navegar por sitios de viajes. El usuario consulta las sugerencias y decide qué sitio visitar.','Hablar de una colaboración','Cómo funciona','Vista de desarrollo','Versión 0.4.4 · Aún no publicada en Chrome Web Store.','Servicios de consumo reconocidos','Sugerencias a la vez','Idiomas del sitio','De navegar a descubrir.',
[['Visita un sitio compatible','El sitio y la categoría de la página se reconocen en tu dispositivo.'],['Explora opciones relevantes','Hasta tres alternativas aparecen en la ventana o en un pequeño panel.'],['Elige dónde ir','La recomendación solo abre una pestaña nueva cuando haces clic.']],
'Una interfaz pequeña. Un paso útil.','Ventana real en coreano capturada en una prueba de desarrollo (v0.4.4). Los nombres identifican servicios y no implican afiliación ni respaldo.','Para distintos momentos del viaje.','El catálogo incluye viajes y servicios relacionados. Reconocer un sitio no significa tener aprobación de afiliación.',
['Alojamiento','Vuelos y transporte','Tours y entradas','eSIM y conectividad','Coches de alquiler y consignas','Compras y servicios relacionados'],
'Un canal de referidos transparente.','Para redes y anunciantes que revisan tráfico de extensiones. Verificamos el permiso de cada programa antes de activar enlaces monetizados.',
[['Visitas iniciadas por el usuario','Sin redirecciones automáticas ni aplicación de enlaces afiliados en segundo plano en sitios reales.'],['Comisiones claramente indicadas','Los enlaces afiliados configurados se identifican. Las compras pueden generar comisiones para el operador de la cuenta configurada.'],['Respeto a la atribución existente','Se conservan los parámetros publisher detectados. No se leen cookies.'],['Activación tras aprobación','Sin configuración aprobada se usan enlaces normales. No hay descuentos ni reembolsos verificados activados actualmente.']],
'Disponible para revisión técnica.','Ofrecemos una versión de desarrollo a petición. El envío a la tienda espera beneficios verificados, aprobación del programa y revisión final. Audiencia, conversiones e ingresos no están verificados.',
'Revisemos la compatibilidad.','Pide a RushLabs una versión de revisión, una explicación del flujo de referidos o una conversación sobre los requisitos de tu programa.','Consultas de colaboración','Imprimir presentación',
'Resumen del tratamiento de datos de la extensión actual y este sitio. La política completa de la extensión está disponible en inglés y coreano.',
[['Procesamiento en el dispositivo','Las URL compatibles y una geometría DOM limitada se procesan localmente. La versión general no envía las URL visitadas a la API de enlaces de producción.'],['Almacenamiento y control','Ajustes, idioma, selección de comparación e identificadores afiliados públicos quedan en el almacenamiento local de la extensión. El procesamiento temporal usa sesión o memoria. Puedes desactivar sugerencias, limitar permisos o desinstalar para eliminar los datos.'],['Destinos externos','Al pulsar un enlace afiliado configurado, el identificador público y el destino pueden enviarse al comercio o red. Se aplican sus políticas. No se solicitan contraseñas ni datos de pago, ni se usan bases de historial o SDK analíticos.'],['Este sitio','Sin analítica, rastreadores publicitarios ni formularios. GitHub Pages puede procesar metadatos de solicitudes para servir el sitio. El idioma puede guardarse en el navegador. Al enviar un correo se comparte su contenido con RushLabs.']],
'Software independiente de RushLabs, Corea del Sur. La aprobación de programas y publicación en tienda son procesos separados de esta presentación.','Volver a la presentación','Actualizado el 8 de octubre de 2026'
]),
'pt-BR': make([
'Português (Brasil)','A extensão','Para parceiros','Privacidade','Idioma','Ir para o conteúdo','pikvia · RUSHLABS','O próximo passo da sua viagem.','Uma extensão do Chrome para descobrir serviços relevantes ao navegar em sites de viagem. O usuário confere as sugestões e escolhe o próximo site.','Conversar sobre parceria','Veja como funciona','Prévia de desenvolvimento','Versão 0.4.4 · Ainda não publicada na Chrome Web Store.','Serviços ao consumidor reconhecidos','Sugestões por vez','Idiomas do site','Da navegação à descoberta.',
[['Visite um site compatível','O site e a categoria da página são reconhecidos no dispositivo.'],['Explore opções relevantes','Até três alternativas aparecem no popup ou em um pequeno painel.'],['Escolha para onde ir','Uma nova aba só é aberta quando o usuário clica na sugestão.']],
'Uma interface pequena. Um passo útil.','Popup real em coreano, capturado em teste de desenvolvimento (v0.4.4). Os nomes identificam serviços e não indicam parceria ou endosso.','Para diferentes etapas da viagem.','O catálogo inclui viagens e serviços relacionados. Reconhecer um site não significa aprovação como afiliado.',
['Hospedagem','Voos e transporte','Passeios e ingressos','eSIM e conectividade','Aluguel de carros e guarda-volumes','Compras e serviços relacionados'],
'Um canal de indicação transparente.','Para redes e anunciantes que avaliam tráfego de extensões. Verificamos a permissão de cada programa antes de ativar links monetizados.',
[['Visitas iniciadas pelo usuário','Sem redirecionamentos automáticos ou aplicação de links afiliados em segundo plano em sites reais.'],['Comissão claramente informada','Links afiliados configurados são identificados. Compras podem gerar comissão ao operador da conta configurada.'],['Respeito à atribuição existente','Parâmetros publisher detectados são preservados. Cookies não são lidos.'],['Ativação após aprovação','Sem configuração aprovada, são usados links comuns. Nenhum desconto ou cashback verificado está ativo atualmente.']],
'Disponível para avaliação técnica.','Uma versão de desenvolvimento está disponível sob solicitação. O envio à loja aguarda benefícios verificados, aprovação dos programas e avaliação final. Público, conversões e receitas não foram verificados.',
'Vamos avaliar a compatibilidade.','Peça à RushLabs uma versão de avaliação, uma apresentação do fluxo de indicações ou uma conversa sobre os requisitos do seu programa.','Contato para parcerias','Imprimir apresentação',
'Resumo do tratamento de dados da extensão atual e deste site. A política completa da extensão está disponível em inglês e coreano.',
[['Processamento no dispositivo','URLs compatíveis e geometria DOM limitada são processadas localmente. A versão geral não envia URLs visitadas à API de links de produção.'],['Armazenamento e controle','Configurações, idioma, seleções de comparação e IDs públicos de afiliado ficam no armazenamento local da extensão. Processamento temporário usa sessão ou memória. Desative sugestões, restrinja permissões ou desinstale para remover os dados.'],['Destinos externos','Ao clicar em um link afiliado configurado, o ID público e o destino podem ser enviados ao comerciante ou rede. Aplicam-se as políticas deles. Sem solicitação de senhas ou dados de pagamento, banco de histórico ou SDKs de análise.'],['Este site','Sem análise, rastreadores de publicidade ou formulários. GitHub Pages pode processar metadados de solicitações para servir o site. O idioma pode ser salvo no navegador. Ao enviar um e-mail, seu conteúdo é compartilhado com a RushLabs.']],
'Software independente da RushLabs, Coreia do Sul. Aprovação de programas e publicação na loja são separadas desta apresentação.','Voltar à apresentação','Atualizado em 8 de outubro de 2026'
]),
it: make([
'Italiano','L’estensione','Per i partner','Privacy','Lingua','Vai al contenuto','pikvia · RUSHLABS','Il prossimo passo del tuo viaggio.','Un’estensione Chrome per scoprire servizi pertinenti mentre navighi sui siti di viaggio. L’utente consulta i suggerimenti e sceglie quale sito visitare.','Parliamo di collaborazione','Come funziona','Anteprima di sviluppo','Versione 0.4.4 · Non ancora pubblicata sul Chrome Web Store.','Servizi per consumatori riconosciuti','Suggerimenti alla volta','Lingue del sito','Dalla navigazione alla scoperta.',
[['Visita un sito supportato','Il sito e la categoria della pagina sono riconosciuti sul dispositivo.'],['Esplora opzioni pertinenti','Fino a tre alternative appaiono nel popup o in un piccolo pannello.'],['Scegli dove andare','Un nuovo tab si apre solo quando l’utente clicca sul suggerimento.']],
'Una piccola interfaccia. Un passo utile.','Popup reale in coreano, acquisito durante un test di sviluppo (v0.4.4). I nomi identificano i servizi senza implicare affiliazione o approvazione.','Per le diverse tappe del viaggio.','Il catalogo comprende viaggi e servizi correlati. Riconoscere un sito non significa avere l’approvazione di affiliazione.',
['Alloggi','Voli e trasporti','Tour e biglietti','eSIM e connessione','Noleggio auto e deposito bagagli','Shopping e servizi correlati'],
'Un canale di referral trasparente.','Per reti e inserzionisti che valutano il traffico delle estensioni. Verifichiamo il permesso di ogni programma prima di attivare link monetizzati.',
[['Visite avviate dall’utente','Nessun reindirizzamento automatico o applicazione di link affiliati in background sui siti reali.'],['Commissioni chiaramente indicate','I link affiliati configurati sono identificati. Gli acquisti possono generare commissioni per il gestore dell’account configurato.'],['Rispetto dell’attribuzione esistente','I parametri publisher rilevati vengono conservati. I cookie non vengono letti.'],['Attivazione dopo approvazione','Senza configurazione approvata si usano link ordinari. Nessuno sconto o cashback verificato è attualmente attivo.']],
'Disponibile per verifica tecnica.','Una build di sviluppo è disponibile su richiesta. L’invio allo store attende vantaggi verificati, approvazione dei programmi e verifica finale. Pubblico, conversioni e ricavi non sono verificati.',
'Valutiamo la compatibilità.','Chiedi a RushLabs una build di verifica, una presentazione del flusso di referral o un confronto sui requisiti del tuo programma.','Richieste di collaborazione','Stampa la presentazione',
'Panoramica del trattamento dei dati dell’estensione attuale e di questo sito. La politica completa dell’estensione è disponibile in inglese e coreano.',
[['Elaborazione sul dispositivo','Gli URL supportati e una geometria DOM limitata sono elaborati localmente. La build generale non invia gli URL visitati all’API di link di produzione.'],['Archiviazione e controllo','Impostazioni, lingua, selezioni di confronto e ID affiliati pubblici restano nell’archivio locale dell’estensione. L’elaborazione temporanea usa sessione o memoria. Disattiva suggerimenti, limita gli accessi o disinstalla per rimuovere i dati.'],['Destinazioni esterne','Un clic su un link affiliato configurato può inviare l’ID pubblico e la destinazione al commerciante o alla rete. Si applicano le loro politiche. Nessuna richiesta di password o dati di pagamento, nessun database di cronologia o SDK analitico.'],['Questo sito','Nessuna analisi, tracker pubblicitario o modulo di contatto. GitHub Pages può elaborare metadati delle richieste per fornire il sito. La lingua può essere salvata nel browser. Le email inviate condividono il contenuto con RushLabs.']],
'Software indipendente di RushLabs, Corea del Sud. Approvazione dei programmi e pubblicazione nello store sono separate da questa presentazione.','Torna alla presentazione','Aggiornato l’8 ottobre 2026'
]),
ar: make([
'العربية','الإضافة','للشركاء','الخصوصية','اللغة','انتقل إلى المحتوى','pikvia · RUSHLABS','خطوة مفيدة تالية لكل رحلة.','إضافة لمتصفح Chrome تساعد المسافرين على اكتشاف خدمات مناسبة أثناء التصفح. يراجع المستخدم الاقتراحات ويختار بنفسه الموقع الذي يريد زيارته.','ناقش الشراكة','كيف تعمل الإضافة','معاينة تطويرية','الإصدار 0.4.4 · لم يُنشر بعد في متجر Chrome الإلكتروني.','خدمات استهلاكية يمكن التعرف عليها','اقتراحات في كل مرة','لغات الموقع','من التصفح إلى الاكتشاف.',
[['تصفح موقعًا مدعومًا','تتعرف الإضافة على الموقع وفئة الصفحة على جهازك.'],['اكتشف الخيارات المناسبة','تظهر حتى ثلاث خدمات بديلة في النافذة المنبثقة أو لوحة صغيرة.'],['اختر وجهتك بنفسك','لا يُفتح رابط الاقتراح في علامة تبويب جديدة إلا عند النقر عليه.']],
'واجهة صغيرة وخطوة مفيدة.','نافذة فعلية باللغة الكورية التُقطت أثناء اختبار واجهة تطويرية (v0.4.4). الأسماء للتعريف بالخدمات ولا تعني وجود شراكة أو تأييد.','لمراحل الرحلة المختلفة.','يشمل الدليل خدمات السفر والخدمات المرتبطة بها. التعرف على موقع لا يعني الموافقة على شراكة تسويق بالعمولة.',
['الإقامة','الرحلات ووسائل النقل','الجولات والتذاكر','eSIM والاتصال','تأجير السيارات وحفظ الأمتعة','التسوق والخدمات المرتبطة'],
'قناة إحالة واضحة.','معلومات للشبكات والمعلنين الذين يراجعون زيارات إضافات المتصفح. نتحقق من إذن كل برنامج قبل تفعيل الروابط المدرة للعمولة.',
[['الزيارة باختيار المستخدم','لا إعادة توجيه تلقائية أو تطبيق لروابط العمولة في الخلفية على المواقع الفعلية.'],['إفصاح واضح عن العمولة','تُميّز روابط العمولة المهيأة في الواجهة. قد ينتج عن الشراء عمولة لمشغل الحساب المهيأ.'],['احترام الإسناد الموجود','تُحفظ معاملات publisher المكتشفة ولا تُقرأ ملفات تعريف الارتباط.'],['التفعيل بعد الموافقة','تُستخدم روابط عادية دون إعداد معتمد. لا توجد خصومات أو استردادات نقدية موثقة مفعلة حاليًا.']],
'متاحة للمراجعة التقنية.','نسخة تطويرية متاحة عند الطلب. التقديم للمتجر مؤجل لحين التحقق من المزايا والحصول على موافقة البرامج والمراجعة النهائية. لم تُوثق أعداد المستخدمين أو التحويلات أو الإيرادات.',
'لنراجع مدى التوافق.','اطلب من RushLabs نسخة للمراجعة أو شرحًا لمسار الإحالة أو مناقشة متطلبات برنامجك لإضافات المتصفح.','استفسارات الشراكة','طباعة التعريف',
'ملخص لمعالجة البيانات في الإضافة الحالية وهذا الموقع. سياسة الإضافة الكاملة متاحة بالإنجليزية والكورية.',
[['المعالجة على الجهاز','تُعالج عناوين الصفحات المدعومة ومعلومات محدودة عن مواضع وأبعاد DOM محليًا. النسخة العامة الحالية لا ترسل عناوين التصفح إلى واجهة روابط الإنتاج.'],['التخزين والتحكم','تُحفظ الإعدادات واللغة وخيارات المقارنة ومعرفات العمولة العامة في تخزين الإضافة المحلي. تستخدم المعالجة المؤقتة الجلسة أو الذاكرة. يمكنك تعطيل الاقتراحات أو تقييد الوصول أو إزالة الإضافة لحذف تخزينها.'],['الوجهات الخارجية','قد يرسل النقر على رابط عمولة مهيأ المعرف العام والوجهة إلى التاجر أو الشبكة. تنطبق سياساتهم. لا تُطلب كلمات مرور أو بيانات دفع ولا توجد قاعدة سجل تصفح أو أدوات تحليل SDK.'],['هذا الموقع','لا أدوات تحليل أو تتبع إعلاني أو نماذج اتصال. قد تعالج GitHub Pages بيانات الطلب الوصفية لخدمة الموقع. قد تُحفظ اللغة المختارة في المتصفح. إرسال رسالة بريد يشارك محتواها مع RushLabs.']],
'برنامج مستقل من RushLabs في كوريا الجنوبية. موافقة البرامج والنشر في المتجر منفصلان عن هذا التعريف.','العودة إلى التعريف','تحديث 8 أكتوبر 2026'
]),
id: make([
'Bahasa Indonesia','Ekstensi','Untuk mitra','Privasi','Bahasa','Ke konten utama','pikvia · RUSHLABS','Langkah berikutnya untuk setiap perjalanan.','Ekstensi Chrome yang membantu wisatawan menemukan layanan relevan saat menjelajah. Pengguna melihat saran dan memilih sendiri situs yang ingin dikunjungi.','Diskusikan kemitraan','Lihat cara kerjanya','Pratinjau pengembangan','Versi 0.4.4 · Belum diterbitkan di Chrome Web Store.','Layanan konsumen yang dikenali','Saran dalam satu waktu','Bahasa situs','Dari menjelajah hingga menemukan.',
[['Kunjungi situs yang didukung','Situs dan kategori halaman dikenali di perangkat Anda.'],['Temukan pilihan relevan','Hingga tiga alternatif muncul di popup atau panel kecil.'],['Pilih tujuan sendiri','Tab baru hanya terbuka saat pengguna mengeklik saran.']],
'Antarmuka kecil. Langkah yang berguna.','Popup nyata dalam bahasa Korea, diambil dalam pengujian UI pengembangan (v0.4.4). Nama layanan hanya untuk identifikasi, bukan tanda afiliasi atau dukungan.','Untuk berbagai tahap perjalanan.','Katalog mencakup perjalanan dan layanan terkait. Pengenalan situs tidak berarti persetujuan afiliasi.',
['Akomodasi','Penerbangan dan transportasi','Tur dan tiket','eSIM dan konektivitas','Sewa mobil dan penitipan bagasi','Belanja dan layanan terkait'],
'Saluran rujukan yang transparan.','Untuk jaringan dan pengiklan yang meninjau lalu lintas ekstensi. Izin setiap program diperiksa sebelum tautan monetisasi diaktifkan.',
[['Kunjungan atas pilihan pengguna','Tidak ada pengalihan otomatis atau penerapan tautan afiliasi di latar belakang pada situs nyata.'],['Komisi dijelaskan dengan jelas','Tautan afiliasi yang dikonfigurasi diberi penanda. Pembelian dapat memberi komisi kepada pengelola akun yang dikonfigurasi.'],['Menghormati atribusi yang ada','Parameter publisher yang terdeteksi dipertahankan. Cookie tidak dibaca.'],['Aktif setelah persetujuan','Tanpa konfigurasi yang disetujui, tautan biasa digunakan. Belum ada diskon atau cashback terverifikasi yang aktif.']],
'Tersedia untuk tinjauan teknis.','Versi pengembangan tersedia atas permintaan. Pengajuan ke toko menunggu manfaat terverifikasi, persetujuan program dan tinjauan akhir. Jumlah pengguna, konversi dan pendapatan belum diverifikasi.',
'Mari meninjau kecocokannya.','Minta versi tinjauan, penjelasan alur rujukan, atau diskusikan persyaratan ekstensi program Anda dengan RushLabs.','Pertanyaan kemitraan','Cetak pengenalan',
'Ringkasan pengolahan data ekstensi saat ini dan situs ini. Kebijakan lengkap ekstensi tersedia dalam bahasa Inggris dan Korea.',
[['Diproses di perangkat','URL halaman yang didukung dan geometri DOM terbatas diproses secara lokal. Versi umum tidak mengirim URL penjelajahan ke API tautan produksi.'],['Penyimpanan dan kontrol','Pengaturan, bahasa, pilihan perbandingan dan ID afiliasi publik tetap di penyimpanan lokal ekstensi. Pemrosesan sementara memakai sesi atau memori. Saran dapat dinonaktifkan, akses situs dibatasi, dan penyimpanan dihapus dengan mencopot ekstensi.'],['Tujuan eksternal','Klik pada tautan afiliasi yang dikonfigurasi dapat mengirim ID publik dan tujuan ke pedagang atau jaringan. Kebijakan mereka berlaku. Tidak meminta kata sandi atau data pembayaran, tidak ada basis riwayat atau SDK analitik.'],['Situs ini','Tanpa analitik, pelacak iklan atau formulir kontak. GitHub Pages dapat memproses metadata permintaan untuk melayani situs. Bahasa pilihan dapat disimpan di browser. Email yang dikirim membagikan isinya kepada RushLabs.']],
'Perangkat lunak independen dari RushLabs, Korea Selatan. Persetujuan program dan publikasi toko terpisah dari pengenalan ini.','Kembali ke pengenalan','Diperbarui 8 Oktober 2026'
])
};
const extras={
en:['Full extension privacy policy (English / Korean)','Business registration','South Korea'],
ko:['전체 확장 개인정보처리방침 (한국어 / 영어)','사업자등록번호','대한민국'],
ja:['拡張機能の完全なプライバシーポリシー（英語・韓国語）','事業者登録番号','韓国'],
'zh-CN':['完整扩展隐私政策（英语 / 韩语）','营业登记号码','韩国'],
'zh-TW':['完整擴充功能隱私政策（英文 / 韓文）','營業登記號碼','韓國'],
de:['Vollständige Erweiterungsrichtlinie (Englisch / Koreanisch)','Unternehmensregistrierung','Südkorea'],
fr:['Politique complète de l’extension (anglais / coréen)','Numéro d’entreprise','Corée du Sud'],
es:['Política completa de la extensión (inglés / coreano)','Registro empresarial','Corea del Sur'],
'pt-BR':['Política completa da extensão (inglês / coreano)','Registro empresarial','Coreia do Sul'],
it:['Politica completa dell’estensione (inglese / coreano)','Registrazione aziendale','Corea del Sud'],
ar:['سياسة الإضافة الكاملة (الإنجليزية / الكورية)','رقم تسجيل النشاط','كوريا الجنوبية'],
id:['Kebijakan lengkap ekstensi (Inggris / Korea)','Nomor registrasi usaha','Korea Selatan']
};
for(const [lang,[fullPolicy,business,country]] of Object.entries(extras)) Object.assign(locales[lang],{fullPolicy,business,country});
// Confirmed brand: "pick via" — choosing through a path, not a claim of discounts.
const brandCopy={
en:['Your next choice, via pikvia.','A name for choosing your way.','pikvia brings “pick” and “via” together: choose through a helpful path. Discover relevant services, then decide where your next click takes you.'],
ko:['여행의 다음 선택, pikvia를 통해.','이름에 담은 선택의 방식.','pikvia는 선택을 뜻하는 “pick”과 “~를 통해”라는 뜻의 “via”를 연결한 이름입니다. 관련 서비스를 발견하고, 다음 방문은 직접 선택하세요.'],
ja:['旅の次の選択を、pikviaを通じて。','自分の道を選ぶための名前。','pikviaは「選ぶ」を意味する“pick”と「〜を通じて」を意味する“via”を合わせた名前です。関連サービスを見つけ、次の訪問先は自分で選びます。'],
'zh-CN':['下一次旅行选择，通过 pikvia。','名字里的选择之道。','pikvia结合了表示“选择”的“pick”和表示“通过”的“via”。发现相关服务，由你自己决定下一次点击去哪里。'],
'zh-TW':['下一個旅程選擇，透過 pikvia。','名字裡的選擇之道。','pikvia結合了代表「選擇」的「pick」與代表「透過」的「via」。探索相關服務，由你自己決定下一次點擊前往哪裡。'],
de:['Ihre nächste Wahl, über pikvia.','Ein Name für Ihren eigenen Weg.','pikvia verbindet „pick“ (auswählen) mit „via“ (über): ein hilfreicher Weg zu Ihrer Wahl. Entdecken Sie passende Dienste und entscheiden Sie selbst über Ihren nächsten Klick.'],
fr:['Votre prochain choix, via pikvia.','Un nom pour choisir votre chemin.','pikvia réunit « pick » (choisir) et « via » (par l’intermédiaire de). Découvrez des services pertinents, puis décidez vous-même de votre prochaine visite.'],
es:['Tu próxima elección, a través de pikvia.','Un nombre para elegir tu camino.','pikvia une «pick» (elegir) y «via» (a través de): un camino útil para decidir. Descubre servicios relevantes y elige adónde te llevará tu próximo clic.'],
'pt-BR':['Sua próxima escolha, por meio da pikvia.','Um nome para escolher seu caminho.','pikvia une “pick” (escolher) e “via” (por meio de): um caminho útil para decidir. Descubra serviços relevantes e escolha o destino do seu próximo clique.'],
it:['La tua prossima scelta, tramite pikvia.','Un nome per scegliere la tua strada.','pikvia unisce “pick” (scegliere) e “via” (tramite): un percorso utile per decidere. Scopri servizi pertinenti e scegli dove ti porterà il prossimo clic.'],
ar:['خيارك التالي، عبر pikvia.','اسم لاختيار طريقك.','يجمع اسم pikvia بين “pick” بمعنى الاختيار و“via” بمعنى عبر: طريق يساعدك على الاختيار. اكتشف خدمات مناسبة ثم قرر بنفسك وجهة نقرتك التالية.'],
id:['Pilihan berikutnya, melalui pikvia.','Nama untuk memilih jalan Anda.','pikvia menggabungkan “pick” (memilih) dan “via” (melalui): jalur yang membantu Anda memilih. Temukan layanan relevan lalu tentukan sendiri tujuan klik berikutnya.']
};
for(const [lang,[headline,brandTitle,brandMeaning]] of Object.entries(brandCopy)) Object.assign(locales[lang],{headline,brandTitle,brandMeaning});
const screenshotLanguage={en:['in Korean','in English'],ko:['한국어 팝업','영어 팝업'],ja:['韓国語ポップアップ','英語ポップアップ'],'zh-CN':['真实韩语','真实英语'],'zh-TW':['實際韓語','實際英語'],de:['koreanisches Popup','englisches Popup'],fr:['en coréen','en anglais'],es:['en coreano','en inglés'],'pt-BR':['em coreano','em inglês'],it:['in coreano','in inglese'],ar:['باللغة الكورية','باللغة الإنجليزية'],id:['bahasa Korea, diambil','bahasa Inggris, diambil']};
for(const [lang,[from,to]] of Object.entries(screenshotLanguage)) locales[lang].screenCaption=locales[lang].screenCaption.replace(from,to);
